/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmpleado;

import ConexionSQL.InsertarData;
import EntidadesPersona.Empleado;
import Logica.Constantes;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author joel
 */
public class AgregarEmpleado extends javax.swing.JDialog {

    Connection conexion;
    InsertarData insertarD;
    Constantes constantes;
    
    public AgregarEmpleado(Usuarios usuarios, boolean modal,Connection conexion,InsertarData insertarD ) {
        super(usuarios, modal);
        initComponents();
        this.insertarD = insertarD;
        this.conexion = conexion;
        this.constantes = new Constantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkButton = new javax.swing.JButton();
        codigotxt = new javax.swing.JLabel();
        apellidotxt = new javax.swing.JLabel();
        telefonotxt = new javax.swing.JLabel();
        NITtxt = new javax.swing.JLabel();
        direcciontxt = new javax.swing.JLabel();
        correoElectronicotxt = new javax.swing.JLabel();
        nombretxt = new javax.swing.JLabel();
        DPItxt = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        apellidoTF = new javax.swing.JTextField();
        telefonoTF = new javax.swing.JTextField();
        DPITF = new javax.swing.JTextField();
        direccionTF = new javax.swing.JTextField();
        correoElectronicoTF = new javax.swing.JTextField();
        NIT_TF = new javax.swing.JTextField();
        codigoTF = new javax.swing.JTextField();
        empleadoFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok.png"))); // NOI18N
        checkButton.setContentAreaFilled(false);
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 100, 100));

        codigotxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        codigotxt.setForeground(new java.awt.Color(0, 0, 0));
        codigotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigotxt.setText("Codigo");
        getContentPane().add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 50));

        apellidotxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        apellidotxt.setForeground(new java.awt.Color(0, 0, 0));
        apellidotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apellidotxt.setText("Apellido");
        getContentPane().add(apellidotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 50));

        telefonotxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        telefonotxt.setForeground(new java.awt.Color(0, 0, 0));
        telefonotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefonotxt.setText("Telefono");
        getContentPane().add(telefonotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 50));

        NITtxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        NITtxt.setForeground(new java.awt.Color(0, 0, 0));
        NITtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NITtxt.setText("NIT");
        getContentPane().add(NITtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 120, 50));

        direcciontxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        direcciontxt.setForeground(new java.awt.Color(0, 0, 0));
        direcciontxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        direcciontxt.setText("Direccion");
        getContentPane().add(direcciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, 50));

        correoElectronicotxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        correoElectronicotxt.setForeground(new java.awt.Color(0, 0, 0));
        correoElectronicotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correoElectronicotxt.setText("Correo Electronico");
        getContentPane().add(correoElectronicotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 230, 50));

        nombretxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(0, 0, 0));
        nombretxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombretxt.setText("Nombre");
        getContentPane().add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 50));

        DPItxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DPItxt.setForeground(new java.awt.Color(0, 0, 0));
        DPItxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DPItxt.setText("DPI");
        getContentPane().add(DPItxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, 50));

        nombreTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nombreTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTFKeyTyped(evt);
            }
        });
        getContentPane().add(nombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, 50));

        apellidoTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        apellidoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoTFKeyTyped(evt);
            }
        });
        getContentPane().add(apellidoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 50));

        telefonoTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        telefonoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTFKeyTyped(evt);
            }
        });
        getContentPane().add(telefonoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, 50));

        DPITF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        DPITF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DPITFKeyTyped(evt);
            }
        });
        getContentPane().add(DPITF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 190, 50));

        direccionTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(direccionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 190, 50));

        correoElectronicoTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(correoElectronicoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 190, 50));

        NIT_TF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(NIT_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 190, 50));

        codigoTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(codigoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 190, 50));

        empleadoFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleadoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empleado.jpg"))); // NOI18N
        getContentPane().add(empleadoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DPITFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DPITFKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros", "Error", JOptionPane.WARNING_MESSAGE);            
        }
        
         
    }//GEN-LAST:event_DPITFKeyTyped

    private void telefonoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTFKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros", "Error", JOptionPane.WARNING_MESSAGE);
            
        }
        
        if (telefonoTF.getText().length() == constantes.LIMITE_NUMERO) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se pueden ingresar mas de 8 numeros","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_telefonoTFKeyTyped

    private void nombreTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTFKeyTyped
        if (!Character.isLetter(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se pueden ingresar letras", "Error", JOptionPane.WARNING_MESSAGE);
            
        }
        
        if (nombreTF.getText().length()== constantes.LIMITE_NOMBRE) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se pueden ingresar mas de 35 letras","Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_nombreTFKeyTyped

    private void apellidoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTFKeyTyped
        if (!Character.isLetter(evt.getKeyChar())) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se pueden ingresar letras", "Error", JOptionPane.WARNING_MESSAGE);
            
        }
        
        if (nombreTF.getText().length()== constantes.LIMITE_NOMBRE) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se pueden ingresar mas de 35 letras","Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_apellidoTFKeyTyped

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        if (faltaInfo()) {
            JOptionPane.showMessageDialog(this, "No se ha ingresado la info escencial","Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String codigo = codigoTF.getText().trim();
            String nombre = nombreTF.getText().trim();
            String apellido = apellidoTF.getText().trim();
            String NIT = NIT_TF.getText().trim();
            String correoElectronico = correoElectronicoTF.getText().trim();
            String direccion = direccionTF.getText().trim();
            String DPI = DPITF.getText().trim();
            int telefono = Integer.parseInt(telefonoTF.getText().trim());
            
            Empleado emplado = new Empleado(nombre, apellido, NIT, correoElectronico, direccion, DPI, telefono, codigo);
            
            try {
                insertarD.crearEmpleado(conexion, emplado);
                JOptionPane.showMessageDialog(this, "Se ha creado el empleado","Felicidades", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se ha podido crear el empleado","Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    private boolean faltaInfo(){
        return codigoTF.getText().trim().isEmpty()||nombreTF.getText().trim().isEmpty()||apellidoTF.getText().trim().isEmpty()|| 
                telefonoTF.getText().trim().isEmpty()||DPITF.getText().trim().isEmpty()||direccionTF.getText().trim().isEmpty()||
                correoElectronicoTF.getText().trim().isEmpty();      
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPITF;
    private javax.swing.JLabel DPItxt;
    private javax.swing.JTextField NIT_TF;
    private javax.swing.JLabel NITtxt;
    private javax.swing.JTextField apellidoTF;
    private javax.swing.JLabel apellidotxt;
    private javax.swing.JButton checkButton;
    private javax.swing.JTextField codigoTF;
    private javax.swing.JLabel codigotxt;
    private javax.swing.JTextField correoElectronicoTF;
    private javax.swing.JLabel correoElectronicotxt;
    private javax.swing.JTextField direccionTF;
    private javax.swing.JLabel direcciontxt;
    private javax.swing.JLabel empleadoFondo;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel nombretxt;
    private javax.swing.JTextField telefonoTF;
    private javax.swing.JLabel telefonotxt;
    // End of variables declaration//GEN-END:variables
}
