/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmpleado;

import ConexionSQL.Consultas;
import SalidaDatos.AnalizadorInputFile;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author joel
 */
public class CargaDatos extends javax.swing.JFrame {

    private InicioEmpleado iEmpleado;
    private String pathTXT;
    private JFileChooser jfile;
    private ArrayList<String> filaAceptada;
    private ArrayList<String> filaDescartada;
    private Consultas consultas;

    /**
     * Creates new form CargaDatos
     *
     * @param iEmpleado
     */
    public CargaDatos(InicioEmpleado iEmpleado, Consultas consultas) {
        this.iEmpleado = iEmpleado;
        this.consultas = consultas;
        jfile = new JFileChooser();
        initComponents();
        desactivarComponentes();
    }

    private void desactivarComponentes() {
        analizarButton.setEnabled(false);
        uploadButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzquierdo = new javax.swing.JPanel();
        txtSelectFile = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        nombretxtTextField = new javax.swing.JTextField();
        analizarButton = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        scrollErrores = new javax.swing.JScrollPane();
        erroresTextArea = new javax.swing.JTextArea();
        uploadButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        txtErrores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelIzquierdo.setBackground(new java.awt.Color(63, 84, 130));
        panelIzquierdo.setForeground(new java.awt.Color(255, 255, 255));

        txtSelectFile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtSelectFile.setForeground(new java.awt.Color(0, 0, 0));
        txtSelectFile.setText("Seleccionar Archivo");

        selectFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mas (1).png"))); // NOI18N
        selectFileButton.setContentAreaFilled(false);
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        nombretxtTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombretxtTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        analizarButton.setBackground(new java.awt.Color(153, 153, 255));
        analizarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        analizarButton.setForeground(new java.awt.Color(0, 0, 0));
        analizarButton.setText("Analizar TXT");
        analizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
        panelIzquierdo.setLayout(panelIzquierdoLayout);
        panelIzquierdoLayout.setHorizontalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzquierdoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nombretxtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelIzquierdoLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(analizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(selectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIzquierdoLayout.setVerticalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(nombretxtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(analizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(panelIzquierdo, java.awt.BorderLayout.LINE_START);

        panelCentral.setBackground(new java.awt.Color(2, 74, 131));
        panelCentral.setForeground(new java.awt.Color(255, 255, 255));

        erroresTextArea.setColumns(20);
        erroresTextArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        erroresTextArea.setRows(5);
        scrollErrores.setViewportView(erroresTextArea);

        uploadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subir (2).png"))); // NOI18N
        uploadButton.setContentAreaFilled(false);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izquierda (1).png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        txtErrores.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtErrores.setForeground(new java.awt.Color(255, 255, 255));
        txtErrores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErrores.setText("Errores");

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(scrollErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                        .addComponent(txtErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                        .addComponent(uploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        iEmpleado.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        jfile.addChoosableFileFilter(new FileNameExtensionFilter("Archivo de texto", "txt"));
        jfile.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfile.setAcceptAllFileFilterUsed(false);
        if (jfile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {            
            try {
                pathTXT=jfile.getSelectedFile().toString();
                mostrarNombreArchivo(); //Nos muestra el nombre de archivo txt seleccionado
                analizarButton.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void mostrarNombreArchivo(){
        String[] direccionTXT = pathTXT.split("/");
        nombretxtTextField.setText(direccionTXT[direccionTXT.length-1]);
    }
    
    private void analizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarButtonActionPerformed
        AnalizadorInputFile analizador = new AnalizadorInputFile();
        analizador.leerTxt(pathTXT);
        
        filaAceptada = analizador.getFilaAceptada();
        filaDescartada = analizador.getFilaDescartada();
        
        for (int i = 0; i < filaDescartada.size(); i++) {
           erroresTextArea.append(filaDescartada.get(i)+"\n");
        }       
        uploadButton.setEnabled(true);
    }//GEN-LAST:event_analizarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea erroresTextArea;
    private javax.swing.JTextField nombretxtTextField;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JScrollPane scrollErrores;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JLabel txtErrores;
    private javax.swing.JLabel txtSelectFile;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
