/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmpleado;

import Main.PantallaInicio;

/**
 *
 * @author joel
 */
public class InicioEmpleado extends javax.swing.JFrame {

    private PantallaInicio pInicio;
    private String nombreTiendaActual;
    /**
     * Creates new form InicioEmpleado
     * @param pInicio
     */
    public InicioEmpleado(PantallaInicio pInicio) {
        this.pInicio = pInicio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblTextoNombreyCodigo = new javax.swing.JLabel();
        lblTetoTienda = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelCentralUp = new javax.swing.JPanel();
        panelCentralDown = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        cargaDatosButton = new javax.swing.JButton();
        panelCentralCenter = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cargaDatosButton2 = new javax.swing.JButton();
        cargaDatosButton3 = new javax.swing.JButton();
        cargaDatosButton4 = new javax.swing.JButton();
        cargaDatosButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelFondoEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelSuperior.setLayout(new java.awt.BorderLayout());

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha Actual");
        panelSuperior.add(lblFecha, java.awt.BorderLayout.EAST);

        lblTextoNombreyCodigo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTextoNombreyCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTextoNombreyCodigo.setText("Nombre_Tienda");
        panelSuperior.add(lblTextoNombreyCodigo, java.awt.BorderLayout.CENTER);

        lblTetoTienda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTetoTienda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTetoTienda.setText("Tienda:");
        panelSuperior.add(lblTetoTienda, java.awt.BorderLayout.WEST);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelCentralUpLayout = new javax.swing.GroupLayout(panelCentralUp);
        panelCentralUp.setLayout(panelCentralUpLayout);
        panelCentralUpLayout.setHorizontalGroup(
            panelCentralUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelCentralUpLayout.setVerticalGroup(
            panelCentralUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelCentral.add(panelCentralUp, java.awt.BorderLayout.NORTH);

        panelCentralDown.setLayout(new java.awt.BorderLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izquierda (1).png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.setPreferredSize(new java.awt.Dimension(80, 80));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panelCentralDown.add(backButton, java.awt.BorderLayout.LINE_END);

        cargaDatosButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cargaDatosButton.setText("Carga Datos");
        cargaDatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosButtonActionPerformed(evt);
            }
        });
        panelCentralDown.add(cargaDatosButton, java.awt.BorderLayout.LINE_START);

        panelCentral.add(panelCentralDown, java.awt.BorderLayout.SOUTH);

        panelCentralCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Tienda");
        panelCentralCenter.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, 60));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Tiempo entre Tiendas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelCentralCenter.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 60));

        cargaDatosButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cargaDatosButton2.setText("Producto");
        cargaDatosButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosButton2ActionPerformed(evt);
            }
        });
        panelCentralCenter.add(cargaDatosButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 160, 60));

        cargaDatosButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cargaDatosButton3.setText("Pedidos");
        cargaDatosButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosButton3ActionPerformed(evt);
            }
        });
        panelCentralCenter.add(cargaDatosButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 160, 60));

        cargaDatosButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cargaDatosButton4.setText("Usuarios");
        cargaDatosButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosButton4ActionPerformed(evt);
            }
        });
        panelCentralCenter.add(cargaDatosButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 160, 60));

        cargaDatosButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cargaDatosButton1.setText("Ventas");
        cargaDatosButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosButton1ActionPerformed(evt);
            }
        });
        panelCentralCenter.add(cargaDatosButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 160, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Crear o modificar datos");
        panelCentralCenter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 350, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compras");
        panelCentralCenter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 160, -1));

        labelFondoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFondoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/centro_comercial.jpg"))); // NOI18N
        panelCentralCenter.add(labelFondoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        panelCentral.add(panelCentralCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        pInicio.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void cargaDatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosButtonActionPerformed
        CargaDatos carga = new CargaDatos(this);
        carga.setVisible(true);
        carga.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_cargaDatosButtonActionPerformed

    private void cargaDatosButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaDatosButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cargaDatosButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaDatosButton2ActionPerformed

    private void cargaDatosButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaDatosButton3ActionPerformed

    private void cargaDatosButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaDatosButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cargaDatosButton;
    private javax.swing.JButton cargaDatosButton1;
    private javax.swing.JButton cargaDatosButton2;
    private javax.swing.JButton cargaDatosButton3;
    private javax.swing.JButton cargaDatosButton4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelFondoEmpleado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTetoTienda;
    private javax.swing.JLabel lblTextoNombreyCodigo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCentralCenter;
    private javax.swing.JPanel panelCentralDown;
    private javax.swing.JPanel panelCentralUp;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
