/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmpleado;

import GUIConsultas.TiempoEntreTiendas;
import ConexionSQL.Consultas;
import ConexionSQL.InsertarData;
import Main.PantallaInicio;
import java.sql.Connection;
import javax.swing.JLabel;

/**
 *
 * @author joel
 */
public class InicioEmpleado extends javax.swing.JFrame {

    private PantallaInicio pInicio;
    private String nombreTiendaActual = "";
    private String fechaActual = "";
    private boolean existenciaDatos;
    private Connection conexion;
    private Consultas consultas;
    private InsertarData insertarD;

    /**
     * Creates new form InicioEmpleado
     *
     * @param pInicio
     * @param existenciaDatos
     * @param consultas
     * @param conexion
     */
    public InicioEmpleado(PantallaInicio pInicio, boolean existenciaDatos, Consultas consultas,
            Connection conexion) {
        this.pInicio = pInicio;
        this.existenciaDatos = existenciaDatos;
        this.consultas = consultas;
        this.conexion = conexion;
        this.insertarD = new InsertarData();
        initComponents();
        controlarComponentes();
    }

    private void controlarComponentes() {
        if (existenciaDatos) {
            activarComponentes();
        } else {
            desactivarComponentes();
        }
    }

    private void activarComponentes() {
        tiendaButton.setEnabled(true);
        tiempoTiendasButton.setEnabled(true);
        productoButton.setEnabled(true);
        usuariosButton.setEnabled(true);
        ventasButton.setEnabled(true);
        pedidosButton.setEnabled(true);

        cargaDatosButton.setEnabled(false);
    }

    private void desactivarComponentes() {
        tiendaButton.setEnabled(false);
        tiempoTiendasButton.setEnabled(false);
        productoButton.setEnabled(false);
        usuariosButton.setEnabled(false);
        ventasButton.setEnabled(false);
        pedidosButton.setEnabled(false);

        cargaDatosButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        txtFechaActual = new javax.swing.JLabel();
        txtNombreTienda = new javax.swing.JLabel();
        txtTienda = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelCentralUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCentralDown = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        cargaDatosButton = new javax.swing.JButton();
        panelCentralCenter = new javax.swing.JPanel();
        tiendaButton = new javax.swing.JButton();
        tiempoTiendasButton = new javax.swing.JButton();
        productoButton = new javax.swing.JButton();
        pedidosButton = new javax.swing.JButton();
        usuariosButton = new javax.swing.JButton();
        ventasButton = new javax.swing.JButton();
        txtCrearModificar = new javax.swing.JLabel();
        txtCompras = new javax.swing.JLabel();
        labelFondoEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelSuperior.setLayout(new java.awt.BorderLayout());

        txtFechaActual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFechaActual.setText("Fecha Actual");
        panelSuperior.add(txtFechaActual, java.awt.BorderLayout.EAST);

        txtNombreTienda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNombreTienda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNombreTienda.setText("Nombre_Tienda");
        panelSuperior.add(txtNombreTienda, java.awt.BorderLayout.CENTER);

        txtTienda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTienda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTienda.setText("Tienda:");
        panelSuperior.add(txtTienda, java.awt.BorderLayout.WEST);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelCentralUp.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTELAF-GUATEMALA.jpg"))); // NOI18N
        panelCentralUp.add(jLabel1, "card2");

        panelCentral.add(panelCentralUp, java.awt.BorderLayout.NORTH);

        panelCentralDown.setLayout(new java.awt.BorderLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/izquierda (1).png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.setPreferredSize(new java.awt.Dimension(80, 80));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panelCentralDown.add(backButton, java.awt.BorderLayout.LINE_END);

        cargaDatosButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cargaDatosButton.setText("Carga Datos");
        cargaDatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosButtonActionPerformed(evt);
            }
        });
        panelCentralDown.add(cargaDatosButton, java.awt.BorderLayout.LINE_START);

        panelCentral.add(panelCentralDown, java.awt.BorderLayout.SOUTH);

        panelCentralCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiendaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tiendaButton.setText("Tienda");
        tiendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiendaButtonActionPerformed(evt);
            }
        });
        panelCentralCenter.add(tiendaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, 60));

        tiempoTiendasButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tiempoTiendasButton.setText("Tiempo entre Tiendas");
        tiempoTiendasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoTiendasButtonActionPerformed(evt);
            }
        });
        panelCentralCenter.add(tiempoTiendasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 60));

        productoButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        productoButton.setText("Producto");
        productoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoButtonActionPerformed(evt);
            }
        });
        panelCentralCenter.add(productoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 160, 60));

        pedidosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pedidosButton.setText("Pedidos");
        pedidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosButtonActionPerformed(evt);
            }
        });
        panelCentralCenter.add(pedidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 160, 60));

        usuariosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usuariosButton.setText("Usuarios");
        usuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosButtonActionPerformed(evt);
            }
        });
        panelCentralCenter.add(usuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 160, 60));

        ventasButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ventasButton.setText("Ventas");
        ventasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasButtonActionPerformed(evt);
            }
        });
        panelCentralCenter.add(ventasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 160, 60));

        txtCrearModificar.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txtCrearModificar.setForeground(new java.awt.Color(0, 0, 0));
        txtCrearModificar.setText("Crear o modificar datos");
        panelCentralCenter.add(txtCrearModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 350, 30));

        txtCompras.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txtCompras.setForeground(new java.awt.Color(0, 0, 0));
        txtCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCompras.setText("Compras");
        panelCentralCenter.add(txtCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 160, -1));

        labelFondoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFondoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/centro_comercial.jpg"))); // NOI18N
        panelCentralCenter.add(labelFondoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        panelCentral.add(panelCentralCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        pInicio.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void cargaDatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosButtonActionPerformed
        CargaDatos carga = new CargaDatos(this, consultas, conexion, pInicio);
        carga.setVisible(true);
        carga.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_cargaDatosButtonActionPerformed

    private void ventasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasButtonActionPerformed
        Ventas ventas = new Ventas(this, conexion, consultas,insertarD);
        ventas.setLocationRelativeTo(this);
        ventas.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_ventasButtonActionPerformed

    private void tiempoTiendasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoTiendasButtonActionPerformed
        TiempoEntreTiendas tiempoT = new TiempoEntreTiendas(this, true, conexion);
        tiempoT.setLocationRelativeTo(this);
        tiempoT.setVisible(true);
    }//GEN-LAST:event_tiempoTiendasButtonActionPerformed

    private void productoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoButtonActionPerformed
        ProductoFrame productoF = new ProductoFrame(this, insertarD, conexion);
        productoF.setLocationRelativeTo(this);
        productoF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_productoButtonActionPerformed

    private void pedidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosButtonActionPerformed
        Pedidos pedidos = new Pedidos(this, conexion, consultas);
        pedidos.setLocationRelativeTo(this);
        pedidos.setVisible(true);
    }//GEN-LAST:event_pedidosButtonActionPerformed

    private void usuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosButtonActionPerformed
        Usuarios usuarios = new Usuarios(this, conexion, insertarD, consultas);
        usuarios.setLocationRelativeTo(this);
        usuarios.setVisible(true);
    }//GEN-LAST:event_usuariosButtonActionPerformed

    private void tiendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiendaButtonActionPerformed
        TiendaFrame tienda = new TiendaFrame(this, insertarD, conexion);
        tienda.setVisible(true);
        tienda.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_tiendaButtonActionPerformed

    public void setTxtFechaActual(String fechaActual) {
        txtFechaActual.setText(fechaActual);
    }

    public void setTxtNombreTienda(String nombreTienda) {
        txtNombreTienda.setText(nombreTienda);
    }

    public String getTxtFechaActual() {
        return txtFechaActual.getText();
    }

    public String getTxtNombreTienda() {
        return txtNombreTienda.getText();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cargaDatosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFondoEmpleado;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCentralCenter;
    private javax.swing.JPanel panelCentralDown;
    private javax.swing.JPanel panelCentralUp;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JButton pedidosButton;
    private javax.swing.JButton productoButton;
    private javax.swing.JButton tiempoTiendasButton;
    private javax.swing.JButton tiendaButton;
    private javax.swing.JLabel txtCompras;
    private javax.swing.JLabel txtCrearModificar;
    private javax.swing.JLabel txtFechaActual;
    private javax.swing.JLabel txtNombreTienda;
    private javax.swing.JLabel txtTienda;
    private javax.swing.JButton usuariosButton;
    private javax.swing.JButton ventasButton;
    // End of variables declaration//GEN-END:variables
}
