/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmpleado;

/**
 *
 * @author joel
 */
public class Tienda extends javax.swing.JFrame {

    private InicioEmpleado inicioE;
    /**
     * Creates new form Tienda
     * @param inicioE
     */
    public Tienda(InicioEmpleado inicioE) {
        this.inicioE = inicioE;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarTiendabutton = new javax.swing.JButton();
        verTiendasButton = new javax.swing.JButton();
        doorButton = new javax.swing.JButton();
        fondoPixie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarTiendabutton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        agregarTiendabutton.setText("Agregar Tienda");
        agregarTiendabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTiendabuttonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarTiendabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, 80));

        verTiendasButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        verTiendasButton.setText("Ver Tiendas");
        verTiendasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTiendasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(verTiendasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 210, 90));

        doorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puerta (1).png"))); // NOI18N
        doorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 100, 100));

        fondoPixie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pixie_Intelaf.jpg"))); // NOI18N
        getContentPane().add(fondoPixie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verTiendasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTiendasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verTiendasButtonActionPerformed

    private void doorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorButtonActionPerformed
        this.setVisible(false);
        inicioE.setVisible(true);
    }//GEN-LAST:event_doorButtonActionPerformed

    private void agregarTiendabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTiendabuttonActionPerformed
        AgregarTienda agregarTienda = new AgregarTienda(this, true);
        agregarTienda.setLocationRelativeTo(this);
        agregarTienda.setVisible(true);
    }//GEN-LAST:event_agregarTiendabuttonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTiendabutton;
    private javax.swing.JButton doorButton;
    private javax.swing.JLabel fondoPixie;
    private javax.swing.JButton verTiendasButton;
    // End of variables declaration//GEN-END:variables
}
