/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author joel
 */
public class EleccionTienda extends javax.swing.JDialog {

    /**
     * Creates new form EleccionTienda
     */
    public EleccionTienda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaCodeTiendasCombo = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        txtCodigoTienda = new javax.swing.JLabel();
        tiendaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaCodeTiendasCombo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        listaCodeTiendasCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(listaCodeTiendasCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 60));

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/okay (85).png"))); // NOI18N
        okButton.setContentAreaFilled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 85, 85));

        txtCodigoTienda.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        txtCodigoTienda.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoTienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCodigoTienda.setText("Codigo Tienda");
        getContentPane().add(txtCodigoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 40));

        tiendaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda (400px).png"))); // NOI18N
        getContentPane().add(tiendaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 410, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> listaCodeTiendasCombo;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel tiendaFondo;
    private javax.swing.JLabel txtCodigoTienda;
    // End of variables declaration//GEN-END:variables
}
