/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import GUICliente.InicioCliente;
import GUIEmpleado.InicioEmpleado;

/**
 *
 * @author joel
 */
public class PantallaInicio extends javax.swing.JFrame {


    public PantallaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vClientesButton = new javax.swing.JButton();
        vEmpleadosButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        fondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vClientesButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vClientesButton.setText("Version Clientes");
        vClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vClientesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vClientesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 51));

        vEmpleadosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vEmpleadosButton.setText("Version Empleados");
        vEmpleadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vEmpleadosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vEmpleadosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 51));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puerta (1).png"))); // NOI18N
        closeButton.setToolTipText("SALIR");
        closeButton.setContentAreaFilled(false);
        closeButton.setPreferredSize(new java.awt.Dimension(100, 100));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        fondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Intelaf_Fisico (1).jpg"))); // NOI18N
        getContentPane().add(fondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void vEmpleadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vEmpleadosButtonActionPerformed
        InicioEmpleado inicioE = new InicioEmpleado(this);
        inicioE.setVisible(true);
        inicioE.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_vEmpleadosButtonActionPerformed

    private void vClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vClientesButtonActionPerformed
        InicioCliente inicioC = new InicioCliente(this);
        inicioC.setVisible(true);
        inicioC.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_vClientesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fondoInicio;
    private javax.swing.JButton vClientesButton;
    private javax.swing.JButton vEmpleadosButton;
    // End of variables declaration//GEN-END:variables
}
